creation_rules:
  - encrypted_regex: '^(apikey|password|username)$'
    path_regex: 'config/.*\.sops\.yaml$'
    age: >-
      age109fzapgarv59gpyu5tgmwgn7j3hwmfs0dhrz3lrqvjy046jxafnse30kvj
  - path_regex: 'config/.*\.sops\.xml$'
    age: >-
      age109fzapgarv59gpyu5tgmwgn7j3hwmfs0dhrz3lrqvjy046jxafnse30kvj
